name: Build and upload Hello Python

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-py

    - name: Verify
      run: echo ${{ steps.docker_build.outputs.digest }}